"""push

Revision ID: e63546b27785
Revises: 
Create Date: 2026-02-13 04:22:09.887667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63546b27785'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('query', sa.String(length=120), nullable=False),
    sa.Column('min_discount', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_alerts_alert_type'), 'deal_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_deal_alerts_device_id'), 'deal_alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_deal_alerts_id'), 'deal_alerts', ['id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('product_url', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_category'), 'deals', ['category'], unique=False)
    op.create_index(op.f('ix_deals_discount_percent'), 'deals', ['discount_percent'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_is_active'), 'deals', ['is_active'], unique=False)
    op.create_index(op.f('ix_deals_marketplace'), 'deals', ['marketplace'], unique=False)
    op.create_table('user_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('keyword', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interests_category'), 'user_interests', ['category'], unique=False)
    op.create_index(op.f('ix_user_interests_device_id'), 'user_interests', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_interests_id'), 'user_interests', ['id'], unique=False)
    op.create_table('favorite_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'deal_id', name='uq_device_favorite_deal')
    )
    op.create_index(op.f('ix_favorite_deals_deal_id'), 'favorite_deals', ['deal_id'], unique=False)
    op.create_index(op.f('ix_favorite_deals_device_id'), 'favorite_deals', ['device_id'], unique=False)
    op.create_index(op.f('ix_favorite_deals_id'), 'favorite_deals', ['id'], unique=False)
    op.create_table('shared_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_deals_deal_id'), 'shared_deals', ['deal_id'], unique=False)
    op.create_index(op.f('ix_shared_deals_device_id'), 'shared_deals', ['device_id'], unique=False)
    op.create_index(op.f('ix_shared_deals_id'), 'shared_deals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_deals_id'), table_name='shared_deals')
    op.drop_index(op.f('ix_shared_deals_device_id'), table_name='shared_deals')
    op.drop_index(op.f('ix_shared_deals_deal_id'), table_name='shared_deals')
    op.drop_table('shared_deals')
    op.drop_index(op.f('ix_favorite_deals_id'), table_name='favorite_deals')
    op.drop_index(op.f('ix_favorite_deals_device_id'), table_name='favorite_deals')
    op.drop_index(op.f('ix_favorite_deals_deal_id'), table_name='favorite_deals')
    op.drop_table('favorite_deals')
    op.drop_index(op.f('ix_user_interests_id'), table_name='user_interests')
    op.drop_index(op.f('ix_user_interests_device_id'), table_name='user_interests')
    op.drop_index(op.f('ix_user_interests_category'), table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_deals_marketplace'), table_name='deals')
    op.drop_index(op.f('ix_deals_is_active'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_discount_percent'), table_name='deals')
    op.drop_index(op.f('ix_deals_category'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_deal_alerts_id'), table_name='deal_alerts')
    op.drop_index(op.f('ix_deal_alerts_device_id'), table_name='deal_alerts')
    op.drop_index(op.f('ix_deal_alerts_alert_type'), table_name='deal_alerts')
    op.drop_table('deal_alerts')
    # ### end Alembic commands ###
